apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-shared-0-tls
spec:
  issuerRef:
    kind: ClusterIssuer
    name: kafka-shared-selfsigned-issuer
  secretName: kafka-shared-0-tls
  commonName: pubsub/kafka-shared-0.kafka-shared-headless
  dnsNames:
    - kafka-shared-0.kafka-shared-headless.pubsub
    - kafka-shared-0.kafka-shared-headless.pubsub.svc
    - kafka-shared-0.kafka-shared-headless.pubsub.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-shared-1-tls
spec:
  issuerRef:
    kind: ClusterIssuer
    name: kafka-shared-selfsigned-issuer
  secretName: kafka-shared-1-tls
  commonName: pubsub/kafka-shared-1.kafka-shared-headless
  dnsNames:
    - kafka-shared-1.kafka-shared-headless.pubsub
    - kafka-shared-1.kafka-shared-headless.pubsub.svc
    - kafka-shared-1.kafka-shared-headless.pubsub.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-shared-2-tls
spec:
  issuerRef:
    kind: ClusterIssuer
    name: kafka-shared-selfsigned-issuer
  secretName: kafka-shared-2-tls
  commonName: pubsub/kafka-shared-2.kafka-shared-headless
  dnsNames:
    - kafka-shared-2.kafka-shared-headless.pubsub
    - kafka-shared-2.kafka-shared-headless.pubsub.svc
    - kafka-shared-2.kafka-shared-headless.pubsub.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-exporter
spec:
  commonName: pubsub/kafka-exporter
  dnsNames:
    - kafka-exporter.pubsub.svc
    - kafka-exporter.pubsub.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: kafka-shared-selfsigned-issuer
  secretName: kafka-exporter-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-shared-tf-applier
spec:
  commonName: pubsub/kafka-shared-tf-applier
  dnsNames:
    - kafka-shared-tf-applier.pubsub
  issuerRef:
    kind: ClusterIssuer
    name: kafka-shared-selfsigned-issuer
  secretName: kafka-shared-tf-applier
