apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream
  - ../../shared/logging
  - certs.yaml

patches:
  - path: kafka-shared-admins.yaml
  - path: refresh-broker-certs.yaml
  - path: refresh-exporter-certs.yaml
