apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream
  - ../../shared/logging
patches:
  - path: admins.yaml
  - path: certs.yaml
  - path: refresh-broker-certs.yaml
  - path: refresh-exporter-certs.yaml
