apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream
  - ../../shared/logging
  - admins.yaml
  - certs.yaml
  - refresh-broker-certs.yaml
  - refresh-exporter-certs.yaml
