apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream
  - ../../shared/logging
  - certs.yaml

components:
  - ../../../shared/opslevel

patches:
  - path: admins.yaml
  - path: opslevel.yaml
  - path: refresh-broker-certs.yaml
  - path: refresh-exporter-certs.yaml
