---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-connect
spec:
  commonName: pubsub/msk-backup-kafka-connect
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: jks.password
        name: msk-backup-kafka-connect-jks-data # the name of the secret that holds the data for jks
  secretName: msk-backup-kafka-connect-cert # the name of the secret that will be loaded with tls assets

