apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: "msk-backup-"

resources:
  - ../generic-base
  - sa.yaml

patches:
  - path: kafka-cert.yaml
  - path: statefulset.yaml
# Example on how to create the secret holding the jks data.
#secretGenerator:
#  - name: msk-backup-kafka-connect-jks-data
#    envs:
#      - ./secrets/jks.properties
#    options:
#      disableNameSuffixHash: true
