apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: "msk-backup-"

# Overwrite the app labels from the base
labels:
  - pairs:
      app.kubernetes.io/name: msk-backup-kafka-connect-cluster
      app: msk-backup-kafka-connect-cluster
    includeTemplates: true
    includeSelectors: true
resources:
  - ../generic-base
  - sa.yaml
  - init-job.yaml

patches:
  - path: kafka-cert.yaml
  - path: statefulset.yaml

configMapGenerator:
  - name: scripts
    files:
      - register_connectors.sh=scripts/register_connectors.sh
  - name: connector-payloads
    files:
      - backup-connector.yaml=connector-payloads/backup-connector.yaml
# Example on how to create the secret holding the jks data.
#secretGenerator:
#  - name: msk-backup-kafka-connect-jks-data
#    envs:
#      - ./secrets/jks.properties
#    options:
#      disableNameSuffixHash: true

