apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - brokers-configmap.yaml
  - lag-monitor.yaml
  - servers.yaml


images:
  - name: docker.io/bitnami/jmx-exporter
    newName: docker.io/bitnamilegacy/jmx-exporter
