# change to trigger release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app.yaml

configMapGenerator:
  - name: kafka-ui-config
    files:
      - rbac.yaml=./config/rbac.yaml
      - auth.yaml=./config/auth.yaml
      - clusters.yaml=./config/clusters.yaml
