apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-shared
  namespace: pubsub
spec:
  template:
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_CFG_SUPER_USERS
              value: "User:CN=pubsub/kafka-shared-0.kafka-shared-headless;User:CN=pubsub/kafka-shared-1.kafka-shared-headless;User:CN=pubsub/kafka-shared-2.kafka-shared-headless"
