fullnameOverride: kafka-shared
replicaCount: 3
kraft:
  enabled: true
  processRoles: broker,controller
  controllerListenerNames: CONTROLLER
  clusterId: OTE4MjEwYTgzMmMxNDE3ZT # cat /proc/sys/kernel/random/uuid | tr -d '-' | base64 | cut -b 1-22
service:
  headless:
    publishNotReadyAddresses: true
zookeeper:
  enabled: false
metrics:
  kafka:
    enabled: true
    certificatesSecret: kafka-exporter-cert
    tlsCert: tls.crt
    tlsKey: tls.key
    tlsCaCert: ca.crt
  jmx:
    enabled: true
auth:
  clientProtocol: mtls
  interBrokerProtocol: tls
  tls:
    type: pem
    existingSecrets:
      - kafka-shared-0-tls
      - kafka-shared-1-tls
      - kafka-shared-2-tls
