fullnameOverride: kafka-shared
replicaCount: 3
kraft:
  enabled: true
  processRoles: broker,controller
  controllerListenerNames: CONTROLLER
  clusterId: OTE4MjEwYTgzMmMxNDE3ZT # cat /proc/sys/kernel/random/uuid | tr -d '-' | base64 | cut -b 1-22
service:
  headless:
    publishNotReadyAddresses: true
zookeeper:
  enabled: false
metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true
