fullnameOverride: kafka-shared
nameOverride: kafka-shared
replicaCount: 3
kraft:
  enabled: true
  processRoles: broker,controller
  controllerListenerNames: CONTROLLER
existingLog4jConfigMap: kafka-log4j-config
service:
  headless:
    publishNotReadyAddresses: true
zookeeper:
  enabled: false
metrics:
  kafka:
    enabled: true
    certificatesSecret: kafka-exporter-cert
    tlsCert: tls.crt
    tlsKey: tls.key
    tlsCaCert: ca.crt
  jmx:
    enabled: true
allowEveryoneIfNoAclFound: false
authorizerClassName: org.apache.kafka.metadata.authorizer.StandardAuthorizer
auth:
  clientProtocol: mtls
  interBrokerProtocol: tls
  controllerProtocol: tls
  tls:
    type: pem
    endpointIdentificationAlgorithm: "" # Default is https and will mean that it will try verify clients address in the passed cert
    existingSecrets:
      - kafka-shared-0-tls
      - kafka-shared-1-tls
      - kafka-shared-2-tls
