apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream
  - ../../shared/logging

images:
  - name: docker.io/bitnami/jmx-exporter
    newName: docker.io/bitnamilegacy/jmx-exporter
  - name: docker.io/bitnami/kafka
    newName: docker.io/bitnamilegacy/kafka
  - name: docker.io/bitnami/kafka-exporter
    newName: quay.io/utilitywarehouse/kafka-exporter
