apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app mm2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
        policy.semaphore.uw.io/name: "mirror-maker-2"
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: *app
          imagePullPolicy: IfNotPresent
          image: bitnami/kafka:3.4
          env:
            - name: KAFKA_HEAP_OPTS
              value: -Xmx4G -Xms4G
          command:
            #  the config is mounted from a config map created in kustomization.yaml
            - sh
            - -ecx
            - /opt/bitnami/kafka/bin/connect-mirror-maker.sh /config/connect-mirror-maker.properties
          resources:
            requests:
              cpu: 400m
              memory: 400Mi
            limits:
              cpu: "2"
              memory: 8000Mi
          volumeMounts:
            - name: mm2-cfg
              mountPath: /config
      volumes:
        - name: mm2-cfg
          configMap:
            name: mm2-cfg
