#!/bin/sh

mkdir -p ${NS}/${NAME}/upstream

# Fetch from helm repo: https://github.com/bitnami/charts/tree/main/bitnami/kafka#installing-the-chart
helm repo add bitnami https://charts.bitnami.com/bitnami
helm template ${BITNAMI_KAFKA_RELEASE} bitnami/kafka --version ${BITNAMI_KAFKA_RELEASE} -f ${VALUES} --set fullnameOverride=${NAME} --set nameOverride=${NAME} --set kraft.clusterId=${KRAFT_CLUSTERID} --set auth.tls.existingSecrets="{${NAME}-0-tls,${NAME}-1-tls,${NAME}-2-tls}" --namespace ${NS} > ${NS}/${NAME}/upstream/kafka.yaml

cat gen-yaml/clean-upstream-kustomize-template.yaml > ${NS}/${NAME}/upstream/kustomization.yaml

if [ ! -f ${NS}/${NAME}/kustomization.yaml ]; then
cat gen-yaml/namespace-kustomize-template.yaml > ${NS}/${NAME}/kustomization.yaml
fi
