---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

components:
  - ../../shared/opslevel

patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: mm2
    patch: |-
      - op: add
        path: /metadata/annotations/app.uw.systems~1description
        value: Mirror maker with flexible setup
      - op: add
        path: /metadata/annotations/app.uw.systems~1tier
        value: tier_4

configMapGenerator:
  - name: mm2-config-template
    files:
      - connect-mirror-maker-template.properties=config/connect-mirror-maker-template.properties
  - name: mm2-log4j-config
    files:
      - connect-log4j.properties=config/connect-log4j.properties
  - name: mm2-jmx-exporter-config
    files:
      - config.yaml=config/jmx-exporter-config.yaml

images:
  - name: bitnami/jmx-exporter
    newName: docker.io/bitnamilegacy/jmx-exporter
  - name: bitnami/kafka
    newName: docker.io/bitnamilegacy/kafka
