---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: mm2-cfg-template
    files:
      - connect-mirror-maker-template.properties=config/connect-mirror-maker-template.properties
