apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-kafka-certificate
  annotations:
    policies.kyverno.io/title: Create certificate for Kafka client
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Deployment, Statefulset
    policies.kyverno.io/description: >-
      This policy creates the kafka client certificate for the annotated targets.
spec:
  # Generate for existing targets
  generateExisting: true
  background: true
  rules:
    # using separate rule for each annotation, as the issuer, cert name and secret name are different for the generated Certificates
    - name: generate-msk-kafka-certificate
      match:
        any:
          - resources:
              annotations:
                uw.systems/msk-kafka-client: "*"
              kinds:
                - Deployment
                - StatefulSet
      generate:
        # Delete certificate if the target is deleted
        synchronize: true
        # Keep the generated certificates if the policy is deleted
        orphanDownstreamOnPolicyDelete: true
        apiVersion: cert-manager.io/v1
        kind: Certificate
        name: "{{request.object.metadata.name}}-gen-msk-kafka-cert"
        namespace: "{{request.namespace}}"
        data:
          spec:
            commonName: '{{request.namespace}}/{{request.object.metadata.annotations."uw.systems/msk-kafka-client"}}'
            duration: 168h0m0s # 7 days validity
            renewBefore: 96h0m0s # renews 4d before expiry to give us room to act if renewal fails.
            issuerRef:
              group: awspca.cert-manager.io
              kind: AWSPCAClusterIssuer
              name: aws-pca
            secretName: "{{request.object.metadata.name}}-gen-msk-kafka-cert"
    - name: generate-uw-hosted-kafka-certificate
      match:
        any:
          - resources:
              annotations:
                uw.systems/uw-hosted-kafka-client: "*"
              kinds:
                - Deployment
                - StatefulSet
      generate:
        # Delete certificate if the target is deleted
        synchronize: true
        # Keep the generated certificates if the policy is deleted
        orphanDownstreamOnPolicyDelete: true
        apiVersion: cert-manager.io/v1
        kind: Certificate
        name: "{{request.object.metadata.name}}-gen-uw-kafka-cert"
        namespace: "{{request.namespace}}"
        data:
          spec:
            commonName: '{{request.namespace}}/{{request.object.metadata.annotations."uw.systems/uw-hosted-kafka-client"}}'
            duration: 168h0m0s # 7 days validity
            renewBefore: 96h0m0s # renews 4d before expiry to give us room to act if renewal fails.
            issuerRef:
              kind: ClusterIssuer
              name: kafka-shared-selfsigned-issuer
            secretName: "{{request.object.metadata.name}}-gen-uw-kafka-cert"
