apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app kafka-lag-monitor
  annotations:
    prometheus.io/path: "/__/metrics"
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
  labels:
    app: *app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      name: *app
      labels:
        app: *app
    spec:
      containers:
      - env:
        - name: PORT
          value: "8081"
        - name: LOG_LEVEL
          value: INFO
        - name: LOG_FORMAT
          value: text
        - name: KAFKA_VERSION
          valueFrom:
            configMapKeyRef:
              key: internal.kafka.broker.version
              name: kafka-brokers
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              key: internal.kafka.brokers
              name: kafka-brokers
        image: registry.uw.systems/telecom/kafka-lag-monitor:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /__/ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: *app
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /__/ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 0
            memory: 0
          limits:
            cpu: 500m
            memory: 500Mi
