#!/bin/sh

# Generate upstream manifests for combined mode (bitnami "default")
mkdir -p combined

# Fetch from helm repo: https://github.com/bitnami/charts/tree/main/bitnami/kafka#installing-the-chart
helm repo add bitnami https://charts.bitnami.com/bitnami
# Namespace is hardcoded by templates in configMap sh scripts and env vars. Try
# to remove namespace fields and patch the rest. Sadly, this will still leave
# things to patch/fix under the statefulset.
helm template ${BITNAMI_KAFKA_RELEASE} bitnami/kafka -f values-combined.yaml --namespace kafka_ns_replace |\
	sed '/namespace:.*/d' |\
	sed 's/kafka_ns_replace/${MY_POD_NAMESPACE}/g' > combined/upstream.yaml
