apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka-cert.yaml
  - kafka-connect.yaml


# Example on how to create the secret holding the jks data.
#secretGenerator:
#  - name: kafka-connect-jks-data
#    envs:
#      - ./secrets/jks.properties
#    options:
#      disableNameSuffixHash: true
