name: Release
on:
  push:
    branches:
      - mhughes/release-please-experiment
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: mhughes/release-please-experiment
