---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: mm2-log4j-config
    files:
      - connect-log4j.properties=config/connect-log4j.properties
  - name: mm2-jmx-exporter-config
    files:
      - config.yaml=config/jmx-exporter-config.yaml
# This configmap should be enabled in the concrete usages of this base
#  - name: mm2-config
#    files:
#      - connect-mirror-maker.properties=config/connect-mirror-maker-sample.properties
